### ISSUE TITLE
[Bug]: Can retain speed infinitely in NoDashTrigger

### ISSUE THREAD

**Issue by LozenChen** [CommunalHelper/CrystallineHelper#19]
### Before You Report

- [X] My mods and Everest install are up to date.
- [X] I have recreated the bug with a minimum number of mods installed.

### What platform are you playing on?

Win10

### Bug Description

keep pressing two dash button bindings in NoDashTrigger, then your speed never lose

where is this bug: Normally in Player.NormalUpdate(), player press dash, then return StartDash() is called and player enters State Dash, so the codes in NormalUpdate() after the "StartDash" part does not matter
however, NoDashTrigger just hooks StartDash(), so in this case when player press dash, return StartDash() is called and nothing happens, and the codes after the "StartDash" part (in particular, those codes about friction) are just ignored!

imo hook CanDash's getter should fix this bug

### Steps to Reproduce

enter NoDashTrigger, then open tas, input
```
1,J
repeat 200
1,X
1,C
endrepeat
```

then your vertical speed will always be -105

**Comment by vitellaryjr** [comment]
issue resolved with pull request #22 , thanks for the suggestion for the solution!
